# Trabajo de dataset con los climas de las cuidades agregados

importamos las librerias necesarias

In [1]:
import pandas as pd
import numpy as np
import Funciones as f
import matplotlib.pyplot as plt
import seaborn as sns

Haremos la limpieza de los datos y la unión de los datasets para poder hacer el análisis de datos

In [2]:
df=pd.read_csv("delivery_events.csv")

In [3]:
f.explorar_df(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  object
 1   load_id             170820 non-null  object
 2   trip_id             170820 non-null  object
 3   event_type          170820 non-null  object
 4   facility_id         170820 non-null  object
 5   scheduled_datetime  170820 non-null  object
 6   actual_datetime     170820 non-null  object
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  object
 10  location_state      170820 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 13.2+ MB
None
Primeras filas
      event_id       load_id       trip_id event_type facility_id  \
0  EVT00000001  LOAD00000001  TRIP00000001     Pickup    FAC00034
1  EVT00000002  LOAD00000001  TRIP00000001   Delivery    FAC00046
2  EVT00000003  LOAD00000002  TRIP00000002     Pickup    FAC00015
3  EVT00000004  LOAD00000002  TRIP00000002   Delivery    FAC00050
4  EVT00000005  LOAD00000003  TRIP00000003     Pickup    FAC00001

           scheduled_datetime             actual_datetime  detention_minutes  \
0  2022-01-01 18:00:00.000000  2022-01-01 20:58:55.918185                  0
1  2022-01-02 23:10:55.918185  2022-01-02 21:30:22.142060                230
2  2022-01-01 18:00:00.000000  2022-01-01 17:37:26.608430                 62
3  2022-01-02 02:13:26.608430  2022-01-02 05:55:46.238257                 67
4  2022-01-01 08:00:00.000000  2022-01-01 07:28:02.169634                 83

   on_time_flag location_city location_state
0         False       Houston             TX
1          True       Detroit             MI
2          True   Kansas City             MO
3         False  Indianapolis             IN
4          True      Columbus             OH
Describe()
                       count  unique                         top   freq  \
event_id              170820  170820                 EVT00000001      1
load_id               170820   85410                LOAD00000001      2
trip_id               170820   85410                TRIP00000001      2
event_type            170820       2                      Pickup  85410
facility_id           170820      50                    FAC00028   3580
scheduled_datetime    170820   99624  2022-02-03 07:00:00.000000     17
actual_datetime       170820  170820  2022-01-01 20:58:55.918185      1
detention_minutes   170820.0     NaN                         NaN    NaN
on_time_flag          170820       2                        True  95095
location_city         170820      20                 Kansas City  14562
location_state        170820      19                          TX  17542

                        mean        std  min   25%   50%    75%    max
event_id                 NaN        NaN  NaN   NaN   NaN    NaN    NaN
load_id                  NaN        NaN  NaN   NaN   NaN    NaN    NaN
trip_id                  NaN        NaN  NaN   NaN   NaN    NaN    NaN
event_type               NaN        NaN  NaN   NaN   NaN    NaN    NaN
facility_id              NaN        NaN  NaN   NaN   NaN    NaN    NaN
scheduled_datetime       NaN        NaN  NaN   NaN   NaN    NaN    NaN
actual_datetime          NaN        NaN  NaN   NaN   NaN    NaN    NaN
detention_minutes   91.53746  68.652514  0.0  29.0  88.0  147.0  239.0
on_time_flag             NaN        NaN  NaN   NaN   NaN    NaN    NaN
location_city            NaN        NaN  NaN   NaN   NaN    NaN    NaN
location_state           NaN        NaN  NaN   NaN   NaN    NaN    NaN
Nulos
Notnnull
Duplicados
0
Tamaño
Filas: 170820 | Columnas: 11

In [4]:
df.columns

Index(['event_id', 'load_id', 'trip_id', 'event_type', 'facility_id',
       'scheduled_datetime', 'actual_datetime', 'detention_minutes',
       'on_time_flag', 'location_city', 'location_state'],
      dtype='object')

In [5]:
columna={'event_id':'id_evento', 'load_id':'id_carga', 'trip_id':'id_viaje', 'event_type':'tipo_evento', 'facility_id':'id_instalación',
'scheduled_datetime':'fecha_hora_programada', 'actual_datetime':'fecha_hora_real', 'detention_minutes':'minutos_de_detención',
'on_time_flag':'indicador_tiempo_en_hora', 'location_city':'ciudad', 'location_state':'estado'}

In [6]:
df=df.rename(columns=columna)

In [7]:
df.head()

,id_evento,id_carga,id_viaje,tipo_evento,id_instalación,fecha_hora_programada,fecha_hora_real,minutos_de_detención,indicador_tiempo_en_hora,ciudad,estado
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
4,EVT00000005,LOAD00000003,TRIP00000003,Pickup,FAC00001,2022-01-01 08:00:00.000000,2022-01-01 07:28:02.169634,83,True,Columbus,OH

veamos el evento

In [8]:
f.categorico(df,"tipo_evento")

tipo_evento
Pickup      85410
Delivery    85410
Name: count, dtype: int64
['Pickup' 'Delivery']
2

Acotaremos nuestro estudio a 7 ciudades

In [9]:
ciudades={"Houston", "Portland", "Detroit", "Kansas City", "Los Angeles", "Miami", "New York"}

In [10]:
df_estudio=f.filtrar_fila(df,"ciudad",ciudades)

In [11]:
df_estudio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66146 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_evento                 66146 non-null  object
 1   id_carga                  66146 non-null  object
 2   id_viaje                  66146 non-null  object
 3   tipo_evento               66146 non-null  object
 4   id_instalación            66146 non-null  object
 5   fecha_hora_programada     66146 non-null  object
 6   fecha_hora_real           66146 non-null  object
 7   minutos_de_detención      66146 non-null  int64
 8   indicador_tiempo_en_hora  66146 non-null  bool
 9   ciudad                    66146 non-null  object
 10  estado                    66146 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 5.6+ MB

Creemos una columna solo con la fecha

In [12]:
df_estudio = f.separa_fecha_hora(df_estudio,"fecha_hora_real")

c:\Users\tachi\Documents\ironhack\Proyecto_final\Funciones.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col].str.extract(r'(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})')[0])
c:\Users\tachi\Documents\ironhack\Proyecto_final\Funciones.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fecha'] = df[col].dt.date
c:\Users\tachi\Documents\ironhack\Proyecto_final\Funciones.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hora'] = df[col].dt.time

In [13]:
df_estudio.head()

,id_evento,id_carga,id_viaje,tipo_evento,id_instalación,fecha_hora_programada,fecha_hora_real,minutos_de_detención,indicador_tiempo_en_hora,ciudad,estado,fecha,hora
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55,0,False,Houston,TX,2022-01-01,20:58:55
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22,230,True,Detroit,MI,2022-01-02,21:30:22
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26,62,True,Kansas City,MO,2022-01-01,17:37:26
5,EVT00000006,LOAD00000003,TRIP00000003,Delivery,FAC00022,2022-01-03 04:28:02.169634,2022-01-03 03:05:02,11,True,Portland,OR,2022-01-03,03:05:02
8,EVT00000009,LOAD00000005,TRIP00000005,Pickup,FAC00046,2022-01-01 08:00:00.000000,2022-01-01 11:51:35,73,False,Houston,TX,2022-01-01,11:51:35

Abramos el csv del clima de houston

In [14]:
df_clima_houston=pd.read_csv('houston.csv')

In [15]:
nombre={"nombre":"ciudad","fecha y hora":"fecha"}

In [16]:
df_clima_houston=df_clima_houston.rename(columns=nombre)

In [17]:
df_clima_houston.head()

,ciudad,fecha,tempmáx,tempmín,temp,sensación térmica máxima,sensación térmica mínima,sensación térmica,rocío,humedad,...,energía solar,índice UV,riesgo severo,amanecer,atardecer,fase lunar,condiciones,descripción,icono,estaciones
0,Houston,2024-01-01,64.2,50.2,59.5,64.2,50.2,59.5,52.8,79.2,...,4.3,3,NaN,2024-01-01T07:17:03,2024-01-01T17:33:09,0.69,"Rain, Overcast",Cloudy skies throughout the day with rain clea...,rain,"KHOU,72059400188,KIAH,KMCJ,72244012918,D0326"
1,Houston,2024-01-02,52.3,43.1,48.0,52.3,37.0,44.8,40.1,74.2,...,2.9,2,NaN,2024-01-02T07:17:17,2024-01-02T17:33:52,0.72,"Rain, Overcast",Cloudy skies throughout the day with late afte...,rain,"KHOU,72059400188,KMCJ,72244012918,D0326"
2,Houston,2024-01-03,57.3,44.8,49.8,57.3,38.5,46.8,44.2,82.0,...,4.8,6,NaN,2024-01-03T07:17:30,2024-01-03T17:34:36,0.75,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,"KHOU,72059400188,KIAH,KMCJ,72244012918,7224301..."
3,Houston,2024-01-04,59.3,44.8,52.4,59.3,40.2,50.9,41.2,67.2,...,4.1,6,NaN,2024-01-04T07:17:41,2024-01-04T17:35:20,0.78,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"KHOU,72059400188,KIAH,KMCJ,72244012918,D0326"
4,Houston,2024-01-05,61.1,48.6,55.2,61.1,42.8,55.0,48.5,80.1,...,3.7,6,NaN,2024-01-05T07:17:50,2024-01-05T17:36:05,0.81,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,"KHOU,72059400188,KMCJ,72244012918,D0326"

In [23]:
df_estudio['fecha'] = pd.to_datetime(df_estudio['fecha'])
df_clima_houston['fecha'] = pd.to_datetime(df_clima_houston['fecha'])

C:\Users\tachi\AppData\Local\Temp\ipykernel_8816\439952301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_estudio['fecha'] = pd.to_datetime(df_estudio['fecha'])

In [24]:
df_union = pd.merge(df_estudio, df_clima_houston, how="left", on=["ciudad", "fecha"])

In [25]:
df_union

,id_evento,id_carga,id_viaje,tipo_evento,id_instalación,fecha_hora_programada,fecha_hora_real,minutos_de_detención,indicador_tiempo_en_hora,ciudad,...,energía solar,índice UV,riesgo severo,amanecer,atardecer,fase lunar,condiciones,descripción,icono,estaciones
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55,0,False,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22,230,True,Detroit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26,62,True,Kansas City,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EVT00000006,LOAD00000003,TRIP00000003,Delivery,FAC00022,2022-01-03 04:28:02.169634,2022-01-03 03:05:02,11,True,Portland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EVT00000009,LOAD00000005,TRIP00000005,Pickup,FAC00046,2022-01-01 08:00:00.000000,2022-01-01 11:51:35,73,False,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66141,EVT00170808,LOAD00085404,TRIP00085404,Delivery,FAC00030,2025-01-02 00:53:01.196218,2025-01-02 04:04:50,126,False,Portland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66142,EVT00170810,LOAD00085405,TRIP00085405,Delivery,FAC00010,2025-01-01 15:26:34.303985,2025-01-01 13:44:17,112,True,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66143,EVT00170815,LOAD00085408,TRIP00085408,Pickup,FAC00034,2024-12-31 14:00:00.000000,2024-12-31 13:45:42,24,True,Kansas City,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66144,EVT00170816,LOAD00085408,TRIP00085408,Delivery,FAC00045,2025-01-01 17:57:42.158981,2025-01-01 15:19:00,126,False,Portland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66145,EVT00170820,LOAD00085410,TRIP00085410,Delivery,FAC00019,2025-01-01 07:30:59.579843,2025-01-01 13:06:58,59,False,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df_houston_final = df_union[df_union["ciudad"] == "Houston"]

In [30]:
df_houston_final.head()

,id_evento,id_carga,id_viaje,tipo_evento,id_instalación,fecha_hora_programada,fecha_hora_real,minutos_de_detención,indicador_tiempo_en_hora,ciudad,...,energía solar,índice UV,riesgo severo,amanecer,atardecer,fase lunar,condiciones,descripción,icono,estaciones
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55,0,False,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"
4,EVT00000009,LOAD00000005,TRIP00000005,Pickup,FAC00046,2022-01-01 08:00:00.000000,2022-01-01 11:51:35,73,False,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"
19,EVT00000051,LOAD00000026,TRIP00000026,Pickup,FAC00041,2022-01-01 16:00:00.000000,2022-01-01 16:30:25,56,True,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"
27,EVT00000071,LOAD00000036,TRIP00000036,Pickup,FAC00023,2022-01-01 12:00:00.000000,2022-01-01 11:51:02,170,True,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"
30,EVT00000075,LOAD00000038,TRIP00000038,Pickup,FAC00032,2022-01-01 07:00:00.000000,2022-01-01 07:13:31,0,True,Houston,...,5.4,4.0,NaN,2022-01-01T07:17:09,2022-01-01T17:33:29,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KHOU,72059400188,KMCJ,72244012918,D0326"

In [31]:
df_houston_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10263 entries, 0 to 66140
Data columns (total 44 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_evento                      10263 non-null  object
 1   id_carga                       10263 non-null  object
 2   id_viaje                       10263 non-null  object
 3   tipo_evento                    10263 non-null  object
 4   id_instalación                 10263 non-null  object
 5   fecha_hora_programada          10263 non-null  object
 6   fecha_hora_real                10263 non-null  datetime64[ns]
 7   minutos_de_detención           10263 non-null  int64
 8   indicador_tiempo_en_hora       10263 non-null  bool
 9   ciudad                         10263 non-null  object
 10  estado                         10263 non-null  object
 11  fecha                          10263 non-null  datetime64[ns]
 12  hora                           10263 non-null  object
 13  tempmáx                        10258 non-null  float64
 14  tempmín                        10258 non-null  float64
 15  temp                           10258 non-null  float64
 16  sensación térmica máxima       10258 non-null  float64
 17  sensación térmica mínima       10258 non-null  float64
 18  sensación térmica              10258 non-null  float64
 19  rocío                          10258 non-null  float64
 20  humedad                        10258 non-null  float64
 21  precipitación                  10258 non-null  float64
 22  probabilidad de precipitación  10258 non-null  float64
 23  cobertura de precipitación     10258 non-null  float64
 24  tipo de precipitación          3470 non-null   object
 25  nieve                          10258 non-null  float64
 26  profundidad de nieve           10258 non-null  float64
 27  ráfaga de viento               10258 non-null  float64
 28  velocidad del viento           10258 non-null  float64
 29  dirección del viento           10258 non-null  float64
 30  presión del nivel del mar      10258 non-null  float64
 31  nubosidad                      10258 non-null  float64
 32  visibilidad                    10258 non-null  float64
 33  radiación solar                10258 non-null  float64
 34  energía solar                  10258 non-null  float64
 35  índice UV                      10258 non-null  float64
 36  riesgo severo                  3927 non-null   float64
 37  amanecer                       10258 non-null  object
 38  atardecer                      10258 non-null  object
 39  fase lunar                     10258 non-null  float64
 40  condiciones                    10258 non-null  object
 41  descripción                    10258 non-null  object
 42  icono                          10258 non-null  object
 43  estaciones                     10258 non-null  object
dtypes: bool(1), datetime64[ns](2), float64(24), int64(1), object(16)
memory usage: 3.5+ MB

In [32]:
f.numerico(df_houston_final,"minutos_de_detención")

count    10263.000000
mean        89.620481
std         67.449583
min          0.000000
25%         28.000000
50%         86.000000
75%        144.000000
max        239.000000
Name: minutos_de_detención, dtype: float64
0
240

In [33]:
f.categorico(df_houston_final,"minutos_de_detención")

minutos_de_detención
0      1355
73       62
92       61
107      59
167      57
       ...
234      11
220      11
216      10
235       9
225       8
Name: count, Length: 240, dtype: int64
[  0  73  56 170  81   8 138  16  38 194  99  83 232  65  22 118 181  35
  14 153  37 131  74 105 151  92  42  10  93  68 143 208 152 148  70  11
  41  54 106 222   6  24  29  64  60 101 172 160 110  80 115  69 167  18
  98 136 176 111 130  61  79  78  86 133 166 226 184  12 150 120  71  94
 186  13 161  19  57  21 145 135  25 185 206  39  62  17 116 103 227 107
 189  96 100  76 122  45 237 142 123 173 146 198  95  34 159   9  33 175
 117 147  31 193 137 164  36 221 187 158 179  51 239 171 205  52 108 141
   7   3 124 155  44 132  43  26 233 128 177 204 174 207 139  97  66 125
   5 154 149  59  48  77 180 218 203 168  90 210 200  75  32  91 156 127
 229 169 162 121 163  47   1  87  30 134   4 202 238 197 144 109  27  28
 236  88 228 104 213 183  50 219  82  23 217 129  49 188  63 113 216 140
  67 102 192  72 234 196  53 199  55  89 112  58 165 114 223 178 215  15
  40 230  46 231 235 157  85  84   2 182 201  20 119 212 126 224 190 195
 225 209 220 191 214 211]
240

In [34]:
f.categorico(df_houston_final,"indicador_tiempo_en_hora")

indicador_tiempo_en_hora
True     5830
False    4433
Name: count, dtype: int64
[False  True]
2

Veamos el data set de rutas

In [36]:
df_rutas=pd.read_csv("rutas.csv")

In [37]:
df_rutas

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3
5,RTE00006,Chicago,IL,Charlotte,NC,675,2.13,0.28,1
6,RTE00007,Dallas,TX,New York,NY,1576,2.54,0.32,2
7,RTE00008,Dallas,TX,Denver,CO,762,2.62,0.15,1
8,RTE00009,Dallas,TX,Indianapolis,IN,878,1.95,0.17,1
9,RTE00010,New York,NY,Philadelphia,PA,92,1.61,0.17,1
10,RTE00011,New York,NY,Columbus,OH,547,1.69,0.24,1
11,RTE00012,Phoenix,AZ,Philadelphia,PA,2389,2.71,0.19,4
12,RTE00013,Phoenix,AZ,Denver,CO,673,1.70,0.21,1
13,RTE00014,Phoenix,AZ,Kansas City,MO,1204,2.14,0.19,2
14,RTE00015,Philadelphia,PA,New York,NY,92,2.79,0.15,1
15,RTE00016,Philadelphia,PA,Seattle,WA,2729,2.50,0.17,4
16,RTE00017,Philadelphia,PA,Minneapolis,MN,1130,1.81,0.34,1
17,RTE00018,Philadelphia,PA,Indianapolis,IN,670,2.07,0.28,1
18,RTE00019,Houston,TX,Detroit,MI,1271,2.33,0.32,2
19,RTE00020,Houston,TX,Seattle,WA,2172,1.77,0.34,3
20,RTE00021,Houston,TX,Portland,OR,2108,2.45,0.28,3
21,RTE00022,Houston,TX,Memphis,TN,557,1.95,0.29,1
22,RTE00023,Miami,FL,Dallas,TX,1276,2.33,0.17,2
23,RTE00024,Miami,FL,Philadelphia,PA,1175,2.48,0.32,2
24,RTE00025,Miami,FL,Seattle,WA,3141,1.65,0.18,5
25,RTE00026,Miami,FL,Denver,CO,1984,1.72,0.28,3
26,RTE00027,Detroit,MI,Houston,TX,1271,2.02,0.33,2
27,RTE00028,Seattle,WA,Houston,TX,2172,1.89,0.26,3
28,RTE00029,Seattle,WA,Charlotte,NC,2623,2.47,0.34,4
29,RTE00030,Seattle,WA,Indianapolis,IN,2147,2.48,0.33,3
30,RTE00031,Denver,CO,Kansas City,MO,640,2.19,0.29,1
31,RTE00032,Portland,OR,Detroit,MI,2259,1.99,0.20,3
32,RTE00033,Portland,OR,Seattle,WA,167,2.42,0.24,1
33,RTE00034,Portland,OR,Columbus,OH,2332,2.12,0.34,4
34,RTE00035,Las Vegas,NV,Dallas,TX,1229,1.69,0.28,2
35,RTE00036,Las Vegas,NV,Los Angeles,CA,262,2.63,0.33,1
36,RTE00037,Las Vegas,NV,New York,NY,2561,1.52,0.21,4
37,RTE00038,Las Vegas,NV,Kansas City,MO,1311,2.71,0.24,2
38,RTE00039,Minneapolis,MN,Atlanta,GA,1044,2.08,0.33,1
39,RTE00040,Minneapolis,MN,Los Angeles,CA,1749,2.38,0.30,3
40,RTE00041,Minneapolis,MN,Houston,TX,1216,2.75,0.21,2
41,RTE00042,Charlotte,NC,Seattle,WA,2623,2.39,0.18,4
42,RTE00043,Charlotte,NC,Denver,CO,1559,1.55,0.16,2
43,RTE00044,Charlotte,NC,Portland,OR,2627,2.69,0.31,4
44,RTE00045,Charlotte,NC,Memphis,TN,597,2.33,0.23,1
45,RTE00046,Columbus,OH,Los Angeles,CA,2269,2.74,0.22,3
46,RTE00047,Columbus,OH,Philadelphia,PA,476,2.06,0.16,1
47,RTE00048,Columbus,OH,Portland,OR,2332,2.69,0.34,4
48,RTE00049,Columbus,OH,Minneapolis,MN,720,2.62,0.20,1
49,RTE00050,Columbus,OH,Kansas City,MO,712,1.94,0.24,1
50,RTE00051,Memphis,TN,Los Angeles,CA,1840,1.85,0.25,3
51,RTE00052,Memphis,TN,Minneapolis,MN,804,1.63,0.34,1
52,RTE00053,Kansas City,MO,Atlanta,GA,777,2.35,0.27,1
53,RTE00054,Kansas City,MO,Los Angeles,CA,1557,2.01,0.19,2
54,RTE00055,Kansas City,MO,Miami,FL,1429,2.51,0.25,2
55,RTE00056,Kansas City,MO,Portland,OR,1718,2.47,0.18,2
56,RTE00057,Kansas City,MO,Charlotte,NC,921,2.45,0.30,1
57,RTE00058,Kansas City,MO,Indianapolis,IN,519,2.27,0.19,1

In [38]:
df_rutas.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     object
 1   origin_city             58 non-null     object
 2   origin_state            58 non-null     object
 3   destination_city        58 non-null     object
 4   destination_state       58 non-null     object
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), object(5)
memory usage: 4.2+ KB

In [39]:
cam={"route_id":"id_ruta","origin_city": "ciudad_origen",	"origin_state": "estado_origen", "destination_city": "ciudad_destino","destination_state" : "estado_destino","typical_distance_miles":" distancia_típica_millas", "base_rate_per_mile": "tarifa_base_por_milla","fuel_surcharge_rate":"tasa_de_recargo_por_combustible", "typical_transit_days":"días_de_tránsito_típicos"}

In [41]:
df_rutas=df_rutas.rename(columns=cam)

In [42]:
df_rutas.head()

,id_ruta,ciudad_origen,estado_origen,ciudad_destino,estado_destino,distancia_típica_millas,tarifa_base_por_milla,tasa_de_recargo_por_combustible,días_de_tránsito_típicos
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3

In [43]:
df_clientes=pd.read_csv("clientes.csv")

In [44]:
df_clientes

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564
...,...,...,...,...,...,...,...,...
195,CUST00196,XYZ Logistics,Spot,60,Retail,Active,2020-04-01,4519111
196,CUST00197,ABC Corp,Contract,15,Consumer Goods,Active,2021-07-02,464753
197,CUST00198,Elite Wholesale,Dedicated,60,Retail,Active,2020-06-09,2242923
198,CUST00199,First Group,Contract,15,General,Active,2020-06-09,1528744
199,CUST00200,XYZ Foods,Dedicated,45,Retail,Inactive,2020-11-02,604239

In [45]:
f.categorico(df_clientes,"customer_name")

customer_name
First Group                 7
First Logistics             5
XYZ Wholesale               4
Continental Supply Chain    4
Metro Wholesale             4
                           ..
Pacific Foods               1
Elite Distribution          1
Pacific Group               1
Premier Supply Chain        1
Elite Wholesale             1
Name: count, Length: 107, dtype: int64
['Metro Wholesale' 'National Retail' 'XYZ Industries' 'American Corp'
 'American Distribution' 'American Industries' 'Superior Distribution'
 'American Logistics' 'XYZ Wholesale' 'National Logistics' 'First Group'
 'ABC Distribution' 'Pacific Corp' 'Elite Foods' 'United Industries'
 'Superior Supply Chain' 'ABC Retail' 'American Supply Chain' 'First Corp'
 'Elite Industries' 'Continental Supply Chain' 'Continental Industries'
 'XYZ Distribution' 'Pacific Retail' 'ABC Supply Chain' 'Superior Foods'
 'ABC Manufacturing' 'American Manufacturing' 'Continental Wholesale'
 'XYZ Foods' 'Elite Retail' 'United Distribution' 'American Retail'
 'ABC Corp' 'First Manufacturing' 'First Logistics' 'First Wholesale'
 'Continental Corp' 'Global Manufacturing' 'Metro Corp'
 'Elite Supply Chain' 'National Corp' 'Continental Retail'
 'Premier Wholesale' 'Global Wholesale' 'Elite Group' 'Premier Group'
 'Superior Group' 'Metro Retail' 'United Retail' 'Metro Supply Chain'
 'Metro Manufacturing' 'Continental Manufacturing'
 'Continental Distribution' 'Pacific Supply Chain' 'First Industries'
 'Elite Corp' 'Metro Group' 'Pacific Logistics' 'First Distribution'
 'ABC Wholesale' 'Global Logistics' 'Metro Logistics' 'United Foods'
 'Pacific Manufacturing' 'Premier Foods' 'Continental Foods'
 'United Group' 'First Foods' 'Continental Logistics' 'National Wholesale'
 'National Supply Chain' 'ABC Foods' 'United Corp' 'Pacific Industries'
 'United Supply Chain' 'Premier Industries' 'Global Distribution'
 'Continental Group' 'Premier Manufacturing' 'Global Corp'
 'Premier Logistics' 'Superior Industries' 'Superior Corp' 'Metro Foods'
 'First Supply Chain' 'XYZ Supply Chain' 'First Retail' 'Global Group'
 'XYZ Group' 'National Distribution' 'Superior Retail' 'Premier Retail'
 'National Foods' 'ABC Group' 'Metro Distribution' 'XYZ Retail'
 'ABC Industries' 'XYZ Logistics' 'Global Foods' 'National Industries'
 'XYZ Corp' 'Pacific Foods' 'Elite Distribution' 'Pacific Group'
 'Premier Supply Chain' 'Elite Wholesale']
107

In [46]:
f.categorico(df_clientes,"primary_freight_type")

primary_freight_type
Automotive        41
Food/Beverage     37
Retail            35
Electronics       33
Consumer Goods    30
General           24
Name: count, dtype: int64
['General' 'Retail' 'Consumer Goods' 'Food/Beverage' 'Automotive'
 'Electronics']
6